### ISSUE TITLE
Metro not working on latest Flutter version 3.10

### ISSUE THREAD

**Issue by Sh1d0w** [nylo-core/framework#32]
Hi. Running

```
metro make:page main_menu --controller
```

Produces an error

```
Deprecated. Use `dart run` instead.
Building package executable... (5.2s)
Built nylo_framework:main.
Unhandled exception:
Unsupported operation: Cannot remove from a fixed-length list
#0      FixedLengthListMixin.removeAt (dart:_internal/list.dart:61:5)
#1      commands (package:nylo_framework/metro/metro.dart:111:13)
```

```
Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale en-US)
```

**Comment by agordn52** [comment]
Hi @Sh1d0w,

Thanks for reporting this, a fix is coming asap.

**Comment by agordn52** [comment]
Hi @Sh1d0w,

If you're using Flutter **v3.10.0**, change your pubspec.yaml file to use the below dependencies:

* intl: ^0.18.0
* nylo_framework: 4.2.1

That should fix the issues you encountered using Metro 👍

Thanks,
Anthony
